includes:
- configs/datasets/mami/with_features.yaml

model_config:
  multi_task:
    training_head_type: classification
    num_labels: 1
    zerobias: true
    biasfill: 0.01
    weightfill: 0.5
    losses:
    - type: bce_kl_combined

dataset_config:
  mami:
    return_features_info: true
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 128

optimizer:
  type: adam_w
  params:
    lr: 5e-5
    eps: 1e-8

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 500
    num_training_steps: ${training.max_updates}

evaluation:
  metrics:
  - type: scoreA
  - type: scoreB
  - type: roc_auc

training:
  batch_size: 16
  lr_scheduler: true
  max_updates: 3000
  find_unused_parameters: true
  early_stop:
    criteria: mami/scoreB
    minimize: false

checkpoint:
  pretrained_state_mapping:
    model.bert: model.bert
